### ISSUE TITLE
remaining codes 

### ISSUE THREAD

**Issue by nsmalotaibi** [NajeebJebreel/DBALFA#1]
Hi Dr. Najeeb,

Firstly, I'd like to extend my heartfelt gratitude for sharing your efforts with the research community. It is truly appreciated.

I was wondering if you could provide the remaining codes necessary for reproducing your main experiments, if possible?

**Comment by najeebjebreel** [comment]
Coming soon.

**Comment by nsmalotaibi** [comment]
Thank you Dr Najeeb.
